import type { CaseworkPageCopy } from "../../contracts/pages/casework";
import { GLOBAL_EN_BUYER_QUESTION } from "../buyer-question";

export const GLOBAL_EN_CASEWORK_PAGE = {
	edition: "global-en",
	page: "casework",
	metadata: {
		title: "Yonaris Casework — One question worked through",
		description: "Follow a representative buyer question from its first answer to evidence, reviewed action, later review and remaining limits.",
	},
	hero: {
		eyebrow: "Representative casework",
		headline: "See one buyer question worked all the way through.",
		body: "One representative record, from the first observation to the reviewed action, the later review, and the limits that remain.",
		disclosure: "Representative casework — not a customer performance claim.",
	},
	representativeLabels: ["Your company", "Alternative A", "Alternative B"],
	timeline: {
		ariaLabel: "Representative evidence timeline",
		stepLabel: "Evidence state",
		previousLabel: "Previous evidence state",
		nextLabel: "Next evidence state",
		recordLabel: "Canonical record",
		questionLabel: "Buyer question",
		baselineLabel: "Baseline",
		laterReviewLabel: "Later observation",
		answersLabel: "Observed answer",
		reasonsLabel: "Decision reason",
		evidenceLabel: "Evidence",
		sourcesLabel: "Source",
		gapsLabel: "Evidence gap",
		actionsLabel: "Reviewed action",
		reviewLabel: "Human review",
		changedLabel: "Changed",
		unchangedLabel: "Unchanged",
		cannotAttributeLabel: "Cannot attribute",
		conditionsLabel: "Review conditions",
		noCommercialOutcomeLabel: "No commercial outcome claimed",
	},
	walkthrough: [
		{ heading: "The situation", body: "Your company appeared in some observations, but the answer gave buyers no clear reason to advance it into the next comparison." },
		{ heading: "The buyer question", body: GLOBAL_EN_BUYER_QUESTION.question },
		{ heading: "What buyers were being told", body: "Alternative A was recommended for documented local-market support. Your company was mentioned, but without the same evidence attached to the reason." },
		{ heading: "What shaped the answer", body: "Alternative A connected its capability, market conditions and public evidence. Your company published the capability, but not the conditions that made it relevant to this question." },
		{ heading: "What was missing or misleading", body: "The capability existed. The missing piece was a public evidence relationship that connected it to the buyer’s selection criterion." },
		{ heading: "What the team changed or validated", body: "The team reviewed one evidence relationship, clarified its scope and supported markets, and attached a source that a buyer could inspect." },
		{ heading: "What was observed afterwards", body: "The reason for considering the company became visible in the later observation. The recommendation order did not change." },
		{ heading: "What still could not be claimed", body: "One review cannot prove that the content change caused the answer change, or that either change produced a commercial outcome." },
	],
	closing: {
		headline: "Curious whether this applies to you?",
		body: "Start with what you are curious about. We can work out whether there is a useful question underneath it.",
		action: { label: "Talk to Yonaris", target: { kind: "page", page: "contact" } },
	},
} as const satisfies CaseworkPageCopy;
