/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as OffSiteAeoRouteImport } from './routes/off-site-aeo'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AgentSplatRouteImport } from './routes/agent.$'
import { Route as AgentApproachRouteImport } from './routes/agent/approach'
import { Route as AgentCompanyRouteImport } from './routes/agent/company'
import { Route as AgentDiagnosticRouteImport } from './routes/agent/diagnostic'
import { Route as AgentGeoRouteImport } from './routes/agent/geo'
import { Route as AgentMethodologyRouteImport } from './routes/agent/methodology'
import { Route as AgentPlatformRouteImport } from './routes/agent/platform'
import { Route as AgentPrivacyRouteImport } from './routes/agent/privacy'
import { Route as AgentProductRouteImport } from './routes/agent/product'
import { Route as AgentResultsRouteImport } from './routes/agent/results'
import { Route as ApiDiagnosticRouteImport } from './routes/api/diagnostic'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ZhApproachRouteImport } from './routes/zh/approach'
import { Route as ZhCompanyRouteImport } from './routes/zh/company'
import { Route as ZhDiagnosticRouteImport } from './routes/zh/diagnostic'
import { Route as ZhGeoRouteImport } from './routes/zh/geo'
import { Route as ZhMethodologyRouteImport } from './routes/zh/methodology'
import { Route as ZhPlatformRouteImport } from './routes/zh/platform'
import { Route as ZhPrivacyRouteImport } from './routes/zh/privacy'
import { Route as ZhProductRouteImport } from './routes/zh/product'
import { Route as ZhResultsRouteImport } from './routes/zh/results'
import { Route as LlmsDotmdxAgentSplatRouteImport } from './routes/llms[.]mdx.agent.$'
import { Route as LlmsDotmdxSiteSplatRouteImport } from './routes/llms[.]mdx.site.$'
import { Route as LlmsDotmdxZhAgentSplatRouteImport } from './routes/llms[.]mdx.zh-agent.$'
import { Route as ZhAgentIndexRouteImport } from './routes/zh/agent/index'
import { Route as ZhAgentSplatRouteImport } from './routes/zh/agent.$'
import { Route as ZhAgentApproachRouteImport } from './routes/zh/agent/approach'
import { Route as ZhAgentCompanyRouteImport } from './routes/zh/agent/company'
import { Route as ZhAgentDiagnosticRouteImport } from './routes/zh/agent/diagnostic'
import { Route as ZhAgentGeoRouteImport } from './routes/zh/agent/geo'
import { Route as ZhAgentPrivacyRouteImport } from './routes/zh/agent/privacy'
import { Route as ZhAgentProductRouteImport } from './routes/zh/agent/product'
import { Route as ApiPlausibleEventIndexRouteImport } from './routes/api/plausible/event/index'
import { Route as ApiPlausibleJsScriptIndexRouteImport } from './routes/api/plausible/js/script/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const OffSiteAeoRoute = OffSiteAeoRouteImport.update({
  id: '/off-site-aeo',
  path: '/off-site-aeo',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSplatRoute = AgentSplatRouteImport.update({
  id: '/agent/$',
  path: '/agent/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentApproachRoute = AgentApproachRouteImport.update({
  id: '/agent/approach',
  path: '/agent/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCompanyRoute = AgentCompanyRouteImport.update({
  id: '/agent/company',
  path: '/agent/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDiagnosticRoute = AgentDiagnosticRouteImport.update({
  id: '/agent/diagnostic',
  path: '/agent/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentGeoRoute = AgentGeoRouteImport.update({
  id: '/agent/geo',
  path: '/agent/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMethodologyRoute = AgentMethodologyRouteImport.update({
  id: '/agent/methodology',
  path: '/agent/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPlatformRoute = AgentPlatformRouteImport.update({
  id: '/agent/platform',
  path: '/agent/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPrivacyRoute = AgentPrivacyRouteImport.update({
  id: '/agent/privacy',
  path: '/agent/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProductRoute = AgentProductRouteImport.update({
  id: '/agent/product',
  path: '/agent/product',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentResultsRoute = AgentResultsRouteImport.update({
  id: '/agent/results',
  path: '/agent/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticRoute = ApiDiagnosticRouteImport.update({
  id: '/api/diagnostic',
  path: '/api/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhApproachRoute = ZhApproachRouteImport.update({
  id: '/zh/approach',
  path: '/zh/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCompanyRoute = ZhCompanyRouteImport.update({
  id: '/zh/company',
  path: '/zh/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhDiagnosticRoute = ZhDiagnosticRouteImport.update({
  id: '/zh/diagnostic',
  path: '/zh/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhGeoRoute = ZhGeoRouteImport.update({
  id: '/zh/geo',
  path: '/zh/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhMethodologyRoute = ZhMethodologyRouteImport.update({
  id: '/zh/methodology',
  path: '/zh/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhPlatformRoute = ZhPlatformRouteImport.update({
  id: '/zh/platform',
  path: '/zh/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhPrivacyRoute = ZhPrivacyRouteImport.update({
  id: '/zh/privacy',
  path: '/zh/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhProductRoute = ZhProductRouteImport.update({
  id: '/zh/product',
  path: '/zh/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhResultsRoute = ZhResultsRouteImport.update({
  id: '/zh/results',
  path: '/zh/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxAgentSplatRoute = LlmsDotmdxAgentSplatRouteImport.update({
  id: '/llms.mdx/agent/$',
  path: '/llms.mdx/agent/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxSiteSplatRoute = LlmsDotmdxSiteSplatRouteImport.update({
  id: '/llms.mdx/site/$',
  path: '/llms.mdx/site/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxZhAgentSplatRoute = LlmsDotmdxZhAgentSplatRouteImport.update({
  id: '/llms.mdx/zh-agent/$',
  path: '/llms.mdx/zh-agent/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAgentIndexRoute = ZhAgentIndexRouteImport.update({
  id: '/zh/agent/',
  path: '/zh/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAgentSplatRoute = ZhAgentSplatRouteImport.update({
  id: '/zh/agent/$',
  path: '/zh/agent/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAgentApproachRoute = ZhAgentApproachRouteImport.update({
  id: '/zh/agent/approach',
  path: '/zh/agent/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAgentCompanyRoute = ZhAgentCompanyRouteImport.update({
  id: '/zh/agent/company',
  path: '/zh/agent/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAgentDiagnosticRoute = ZhAgentDiagnosticRouteImport.update({
  id: '/zh/agent/diagnostic',
  path: '/zh/agent/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAgentGeoRoute = ZhAgentGeoRouteImport.update({
  id: '/zh/agent/geo',
  path: '/zh/agent/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAgentPrivacyRoute = ZhAgentPrivacyRouteImport.update({
  id: '/zh/agent/privacy',
  path: '/zh/agent/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAgentProductRoute = ZhAgentProductRouteImport.update({
  id: '/zh/agent/product',
  path: '/zh/agent/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlausibleEventIndexRoute = ApiPlausibleEventIndexRouteImport.update({
  id: '/api/plausible/event/',
  path: '/api/plausible/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlausibleJsScriptIndexRoute =
  ApiPlausibleJsScriptIndexRouteImport.update({
    id: '/api/plausible/js/script/',
    path: '/api/plausible/js/script/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/company': typeof CompanyRoute
  '/diagnostic': typeof DiagnosticRoute
  '/features': typeof FeaturesRoute
  '/geo': typeof GeoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/results': typeof ResultsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/agent/$': typeof AgentSplatRoute
  '/agent/approach': typeof AgentApproachRoute
  '/agent/company': typeof AgentCompanyRoute
  '/agent/diagnostic': typeof AgentDiagnosticRoute
  '/agent/geo': typeof AgentGeoRoute
  '/agent/methodology': typeof AgentMethodologyRoute
  '/agent/platform': typeof AgentPlatformRoute
  '/agent/privacy': typeof AgentPrivacyRoute
  '/agent/product': typeof AgentProductRoute
  '/agent/results': typeof AgentResultsRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
  '/zh/approach': typeof ZhApproachRoute
  '/zh/company': typeof ZhCompanyRoute
  '/zh/diagnostic': typeof ZhDiagnosticRoute
  '/zh/geo': typeof ZhGeoRoute
  '/zh/methodology': typeof ZhMethodologyRoute
  '/zh/platform': typeof ZhPlatformRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/product': typeof ZhProductRoute
  '/zh/results': typeof ZhResultsRoute
  '/agent/': typeof AgentIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/llms.mdx/agent/$': typeof LlmsDotmdxAgentSplatRoute
  '/llms.mdx/site/$': typeof LlmsDotmdxSiteSplatRoute
  '/llms.mdx/zh-agent/$': typeof LlmsDotmdxZhAgentSplatRoute
  '/zh/agent/$': typeof ZhAgentSplatRoute
  '/zh/agent/approach': typeof ZhAgentApproachRoute
  '/zh/agent/company': typeof ZhAgentCompanyRoute
  '/zh/agent/diagnostic': typeof ZhAgentDiagnosticRoute
  '/zh/agent/geo': typeof ZhAgentGeoRoute
  '/zh/agent/privacy': typeof ZhAgentPrivacyRoute
  '/zh/agent/product': typeof ZhAgentProductRoute
  '/zh/agent/': typeof ZhAgentIndexRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/company': typeof CompanyRoute
  '/diagnostic': typeof DiagnosticRoute
  '/features': typeof FeaturesRoute
  '/geo': typeof GeoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/results': typeof ResultsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/agent/$': typeof AgentSplatRoute
  '/agent/approach': typeof AgentApproachRoute
  '/agent/company': typeof AgentCompanyRoute
  '/agent/diagnostic': typeof AgentDiagnosticRoute
  '/agent/geo': typeof AgentGeoRoute
  '/agent/methodology': typeof AgentMethodologyRoute
  '/agent/platform': typeof AgentPlatformRoute
  '/agent/privacy': typeof AgentPrivacyRoute
  '/agent/product': typeof AgentProductRoute
  '/agent/results': typeof AgentResultsRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
  '/zh/approach': typeof ZhApproachRoute
  '/zh/company': typeof ZhCompanyRoute
  '/zh/diagnostic': typeof ZhDiagnosticRoute
  '/zh/geo': typeof ZhGeoRoute
  '/zh/methodology': typeof ZhMethodologyRoute
  '/zh/platform': typeof ZhPlatformRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/product': typeof ZhProductRoute
  '/zh/results': typeof ZhResultsRoute
  '/agent': typeof AgentIndexRoute
  '/zh': typeof ZhIndexRoute
  '/llms.mdx/agent/$': typeof LlmsDotmdxAgentSplatRoute
  '/llms.mdx/site/$': typeof LlmsDotmdxSiteSplatRoute
  '/llms.mdx/zh-agent/$': typeof LlmsDotmdxZhAgentSplatRoute
  '/zh/agent/$': typeof ZhAgentSplatRoute
  '/zh/agent/approach': typeof ZhAgentApproachRoute
  '/zh/agent/company': typeof ZhAgentCompanyRoute
  '/zh/agent/diagnostic': typeof ZhAgentDiagnosticRoute
  '/zh/agent/geo': typeof ZhAgentGeoRoute
  '/zh/agent/privacy': typeof ZhAgentPrivacyRoute
  '/zh/agent/product': typeof ZhAgentProductRoute
  '/zh/agent': typeof ZhAgentIndexRoute
  '/api/plausible/event': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/company': typeof CompanyRoute
  '/diagnostic': typeof DiagnosticRoute
  '/features': typeof FeaturesRoute
  '/geo': typeof GeoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/results': typeof ResultsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/agent/$': typeof AgentSplatRoute
  '/agent/approach': typeof AgentApproachRoute
  '/agent/company': typeof AgentCompanyRoute
  '/agent/diagnostic': typeof AgentDiagnosticRoute
  '/agent/geo': typeof AgentGeoRoute
  '/agent/methodology': typeof AgentMethodologyRoute
  '/agent/platform': typeof AgentPlatformRoute
  '/agent/privacy': typeof AgentPrivacyRoute
  '/agent/product': typeof AgentProductRoute
  '/agent/results': typeof AgentResultsRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
  '/zh/approach': typeof ZhApproachRoute
  '/zh/company': typeof ZhCompanyRoute
  '/zh/diagnostic': typeof ZhDiagnosticRoute
  '/zh/geo': typeof ZhGeoRoute
  '/zh/methodology': typeof ZhMethodologyRoute
  '/zh/platform': typeof ZhPlatformRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/product': typeof ZhProductRoute
  '/zh/results': typeof ZhResultsRoute
  '/agent/': typeof AgentIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/llms.mdx/agent/$': typeof LlmsDotmdxAgentSplatRoute
  '/llms.mdx/site/$': typeof LlmsDotmdxSiteSplatRoute
  '/llms.mdx/zh-agent/$': typeof LlmsDotmdxZhAgentSplatRoute
  '/zh/agent/$': typeof ZhAgentSplatRoute
  '/zh/agent/approach': typeof ZhAgentApproachRoute
  '/zh/agent/company': typeof ZhAgentCompanyRoute
  '/zh/agent/diagnostic': typeof ZhAgentDiagnosticRoute
  '/zh/agent/geo': typeof ZhAgentGeoRoute
  '/zh/agent/privacy': typeof ZhAgentPrivacyRoute
  '/zh/agent/product': typeof ZhAgentProductRoute
  '/zh/agent/': typeof ZhAgentIndexRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approach'
    | '/company'
    | '/diagnostic'
    | '/features'
    | '/geo'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/methodology'
    | '/off-site-aeo'
    | '/og.png'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/results'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vision'
    | '/agent/$'
    | '/agent/approach'
    | '/agent/company'
    | '/agent/diagnostic'
    | '/agent/geo'
    | '/agent/methodology'
    | '/agent/platform'
    | '/agent/privacy'
    | '/agent/product'
    | '/agent/results'
    | '/api/diagnostic'
    | '/zh/approach'
    | '/zh/company'
    | '/zh/diagnostic'
    | '/zh/geo'
    | '/zh/methodology'
    | '/zh/platform'
    | '/zh/privacy'
    | '/zh/product'
    | '/zh/results'
    | '/agent/'
    | '/zh/'
    | '/llms.mdx/agent/$'
    | '/llms.mdx/site/$'
    | '/llms.mdx/zh-agent/$'
    | '/zh/agent/$'
    | '/zh/agent/approach'
    | '/zh/agent/company'
    | '/zh/agent/diagnostic'
    | '/zh/agent/geo'
    | '/zh/agent/privacy'
    | '/zh/agent/product'
    | '/zh/agent/'
    | '/api/plausible/event/'
    | '/api/plausible/js/script/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approach'
    | '/company'
    | '/diagnostic'
    | '/features'
    | '/geo'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/methodology'
    | '/off-site-aeo'
    | '/og.png'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/results'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vision'
    | '/agent/$'
    | '/agent/approach'
    | '/agent/company'
    | '/agent/diagnostic'
    | '/agent/geo'
    | '/agent/methodology'
    | '/agent/platform'
    | '/agent/privacy'
    | '/agent/product'
    | '/agent/results'
    | '/api/diagnostic'
    | '/zh/approach'
    | '/zh/company'
    | '/zh/diagnostic'
    | '/zh/geo'
    | '/zh/methodology'
    | '/zh/platform'
    | '/zh/privacy'
    | '/zh/product'
    | '/zh/results'
    | '/agent'
    | '/zh'
    | '/llms.mdx/agent/$'
    | '/llms.mdx/site/$'
    | '/llms.mdx/zh-agent/$'
    | '/zh/agent/$'
    | '/zh/agent/approach'
    | '/zh/agent/company'
    | '/zh/agent/diagnostic'
    | '/zh/agent/geo'
    | '/zh/agent/privacy'
    | '/zh/agent/product'
    | '/zh/agent'
    | '/api/plausible/event'
    | '/api/plausible/js/script'
  id:
    | '__root__'
    | '/'
    | '/approach'
    | '/company'
    | '/diagnostic'
    | '/features'
    | '/geo'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/methodology'
    | '/off-site-aeo'
    | '/og.png'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/results'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/vision'
    | '/agent/$'
    | '/agent/approach'
    | '/agent/company'
    | '/agent/diagnostic'
    | '/agent/geo'
    | '/agent/methodology'
    | '/agent/platform'
    | '/agent/privacy'
    | '/agent/product'
    | '/agent/results'
    | '/api/diagnostic'
    | '/zh/approach'
    | '/zh/company'
    | '/zh/diagnostic'
    | '/zh/geo'
    | '/zh/methodology'
    | '/zh/platform'
    | '/zh/privacy'
    | '/zh/product'
    | '/zh/results'
    | '/agent/'
    | '/zh/'
    | '/llms.mdx/agent/$'
    | '/llms.mdx/site/$'
    | '/llms.mdx/zh-agent/$'
    | '/zh/agent/$'
    | '/zh/agent/approach'
    | '/zh/agent/company'
    | '/zh/agent/diagnostic'
    | '/zh/agent/geo'
    | '/zh/agent/privacy'
    | '/zh/agent/product'
    | '/zh/agent/'
    | '/api/plausible/event/'
    | '/api/plausible/js/script/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproachRoute: typeof ApproachRoute
  CompanyRoute: typeof CompanyRoute
  DiagnosticRoute: typeof DiagnosticRoute
  FeaturesRoute: typeof FeaturesRoute
  GeoRoute: typeof GeoRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MethodologyRoute: typeof MethodologyRoute
  OffSiteAeoRoute: typeof OffSiteAeoRoute
  OgDotpngRoute: typeof OgDotpngRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  ResultsRoute: typeof ResultsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisionRoute: typeof VisionRoute
  AgentSplatRoute: typeof AgentSplatRoute
  AgentApproachRoute: typeof AgentApproachRoute
  AgentCompanyRoute: typeof AgentCompanyRoute
  AgentDiagnosticRoute: typeof AgentDiagnosticRoute
  AgentGeoRoute: typeof AgentGeoRoute
  AgentMethodologyRoute: typeof AgentMethodologyRoute
  AgentPlatformRoute: typeof AgentPlatformRoute
  AgentPrivacyRoute: typeof AgentPrivacyRoute
  AgentProductRoute: typeof AgentProductRoute
  AgentResultsRoute: typeof AgentResultsRoute
  ApiDiagnosticRoute: typeof ApiDiagnosticRoute
  ZhApproachRoute: typeof ZhApproachRoute
  ZhCompanyRoute: typeof ZhCompanyRoute
  ZhDiagnosticRoute: typeof ZhDiagnosticRoute
  ZhGeoRoute: typeof ZhGeoRoute
  ZhMethodologyRoute: typeof ZhMethodologyRoute
  ZhPlatformRoute: typeof ZhPlatformRoute
  ZhPrivacyRoute: typeof ZhPrivacyRoute
  ZhProductRoute: typeof ZhProductRoute
  ZhResultsRoute: typeof ZhResultsRoute
  AgentIndexRoute: typeof AgentIndexRoute
  ZhIndexRoute: typeof ZhIndexRoute
  LlmsDotmdxAgentSplatRoute: typeof LlmsDotmdxAgentSplatRoute
  LlmsDotmdxSiteSplatRoute: typeof LlmsDotmdxSiteSplatRoute
  LlmsDotmdxZhAgentSplatRoute: typeof LlmsDotmdxZhAgentSplatRoute
  ZhAgentSplatRoute: typeof ZhAgentSplatRoute
  ZhAgentApproachRoute: typeof ZhAgentApproachRoute
  ZhAgentCompanyRoute: typeof ZhAgentCompanyRoute
  ZhAgentDiagnosticRoute: typeof ZhAgentDiagnosticRoute
  ZhAgentGeoRoute: typeof ZhAgentGeoRoute
  ZhAgentPrivacyRoute: typeof ZhAgentPrivacyRoute
  ZhAgentProductRoute: typeof ZhAgentProductRoute
  ZhAgentIndexRoute: typeof ZhAgentIndexRoute
  ApiPlausibleEventIndexRoute: typeof ApiPlausibleEventIndexRoute
  ApiPlausibleJsScriptIndexRoute: typeof ApiPlausibleJsScriptIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-site-aeo': {
      id: '/off-site-aeo'
      path: '/off-site-aeo'
      fullPath: '/off-site-aeo'
      preLoaderRoute: typeof OffSiteAeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$': {
      id: '/agent/$'
      path: '/agent/$'
      fullPath: '/agent/$'
      preLoaderRoute: typeof AgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/approach': {
      id: '/agent/approach'
      path: '/agent/approach'
      fullPath: '/agent/approach'
      preLoaderRoute: typeof AgentApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/company': {
      id: '/agent/company'
      path: '/agent/company'
      fullPath: '/agent/company'
      preLoaderRoute: typeof AgentCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/diagnostic': {
      id: '/agent/diagnostic'
      path: '/agent/diagnostic'
      fullPath: '/agent/diagnostic'
      preLoaderRoute: typeof AgentDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/geo': {
      id: '/agent/geo'
      path: '/agent/geo'
      fullPath: '/agent/geo'
      preLoaderRoute: typeof AgentGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/methodology': {
      id: '/agent/methodology'
      path: '/agent/methodology'
      fullPath: '/agent/methodology'
      preLoaderRoute: typeof AgentMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/platform': {
      id: '/agent/platform'
      path: '/agent/platform'
      fullPath: '/agent/platform'
      preLoaderRoute: typeof AgentPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/privacy': {
      id: '/agent/privacy'
      path: '/agent/privacy'
      fullPath: '/agent/privacy'
      preLoaderRoute: typeof AgentPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/product': {
      id: '/agent/product'
      path: '/agent/product'
      fullPath: '/agent/product'
      preLoaderRoute: typeof AgentProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/results': {
      id: '/agent/results'
      path: '/agent/results'
      fullPath: '/agent/results'
      preLoaderRoute: typeof AgentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostic': {
      id: '/api/diagnostic'
      path: '/api/diagnostic'
      fullPath: '/api/diagnostic'
      preLoaderRoute: typeof ApiDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/approach': {
      id: '/zh/approach'
      path: '/zh/approach'
      fullPath: '/zh/approach'
      preLoaderRoute: typeof ZhApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/company': {
      id: '/zh/company'
      path: '/zh/company'
      fullPath: '/zh/company'
      preLoaderRoute: typeof ZhCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/diagnostic': {
      id: '/zh/diagnostic'
      path: '/zh/diagnostic'
      fullPath: '/zh/diagnostic'
      preLoaderRoute: typeof ZhDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/geo': {
      id: '/zh/geo'
      path: '/zh/geo'
      fullPath: '/zh/geo'
      preLoaderRoute: typeof ZhGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/methodology': {
      id: '/zh/methodology'
      path: '/zh/methodology'
      fullPath: '/zh/methodology'
      preLoaderRoute: typeof ZhMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/platform': {
      id: '/zh/platform'
      path: '/zh/platform'
      fullPath: '/zh/platform'
      preLoaderRoute: typeof ZhPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/privacy': {
      id: '/zh/privacy'
      path: '/zh/privacy'
      fullPath: '/zh/privacy'
      preLoaderRoute: typeof ZhPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/product': {
      id: '/zh/product'
      path: '/zh/product'
      fullPath: '/zh/product'
      preLoaderRoute: typeof ZhProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/results': {
      id: '/zh/results'
      path: '/zh/results'
      fullPath: '/zh/results'
      preLoaderRoute: typeof ZhResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/agent/$': {
      id: '/llms.mdx/agent/$'
      path: '/llms.mdx/agent/$'
      fullPath: '/llms.mdx/agent/$'
      preLoaderRoute: typeof LlmsDotmdxAgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/site/$': {
      id: '/llms.mdx/site/$'
      path: '/llms.mdx/site/$'
      fullPath: '/llms.mdx/site/$'
      preLoaderRoute: typeof LlmsDotmdxSiteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/zh-agent/$': {
      id: '/llms.mdx/zh-agent/$'
      path: '/llms.mdx/zh-agent/$'
      fullPath: '/llms.mdx/zh-agent/$'
      preLoaderRoute: typeof LlmsDotmdxZhAgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/agent/': {
      id: '/zh/agent/'
      path: '/zh/agent'
      fullPath: '/zh/agent/'
      preLoaderRoute: typeof ZhAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/agent/$': {
      id: '/zh/agent/$'
      path: '/zh/agent/$'
      fullPath: '/zh/agent/$'
      preLoaderRoute: typeof ZhAgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/agent/approach': {
      id: '/zh/agent/approach'
      path: '/zh/agent/approach'
      fullPath: '/zh/agent/approach'
      preLoaderRoute: typeof ZhAgentApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/agent/company': {
      id: '/zh/agent/company'
      path: '/zh/agent/company'
      fullPath: '/zh/agent/company'
      preLoaderRoute: typeof ZhAgentCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/agent/diagnostic': {
      id: '/zh/agent/diagnostic'
      path: '/zh/agent/diagnostic'
      fullPath: '/zh/agent/diagnostic'
      preLoaderRoute: typeof ZhAgentDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/agent/geo': {
      id: '/zh/agent/geo'
      path: '/zh/agent/geo'
      fullPath: '/zh/agent/geo'
      preLoaderRoute: typeof ZhAgentGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/agent/privacy': {
      id: '/zh/agent/privacy'
      path: '/zh/agent/privacy'
      fullPath: '/zh/agent/privacy'
      preLoaderRoute: typeof ZhAgentPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/agent/product': {
      id: '/zh/agent/product'
      path: '/zh/agent/product'
      fullPath: '/zh/agent/product'
      preLoaderRoute: typeof ZhAgentProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plausible/event/': {
      id: '/api/plausible/event/'
      path: '/api/plausible/event'
      fullPath: '/api/plausible/event/'
      preLoaderRoute: typeof ApiPlausibleEventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plausible/js/script/': {
      id: '/api/plausible/js/script/'
      path: '/api/plausible/js/script'
      fullPath: '/api/plausible/js/script/'
      preLoaderRoute: typeof ApiPlausibleJsScriptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproachRoute: ApproachRoute,
  CompanyRoute: CompanyRoute,
  DiagnosticRoute: DiagnosticRoute,
  FeaturesRoute: FeaturesRoute,
  GeoRoute: GeoRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MethodologyRoute: MethodologyRoute,
  OffSiteAeoRoute: OffSiteAeoRoute,
  OgDotpngRoute: OgDotpngRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  ResultsRoute: ResultsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisionRoute: VisionRoute,
  AgentSplatRoute: AgentSplatRoute,
  AgentApproachRoute: AgentApproachRoute,
  AgentCompanyRoute: AgentCompanyRoute,
  AgentDiagnosticRoute: AgentDiagnosticRoute,
  AgentGeoRoute: AgentGeoRoute,
  AgentMethodologyRoute: AgentMethodologyRoute,
  AgentPlatformRoute: AgentPlatformRoute,
  AgentPrivacyRoute: AgentPrivacyRoute,
  AgentProductRoute: AgentProductRoute,
  AgentResultsRoute: AgentResultsRoute,
  ApiDiagnosticRoute: ApiDiagnosticRoute,
  ZhApproachRoute: ZhApproachRoute,
  ZhCompanyRoute: ZhCompanyRoute,
  ZhDiagnosticRoute: ZhDiagnosticRoute,
  ZhGeoRoute: ZhGeoRoute,
  ZhMethodologyRoute: ZhMethodologyRoute,
  ZhPlatformRoute: ZhPlatformRoute,
  ZhPrivacyRoute: ZhPrivacyRoute,
  ZhProductRoute: ZhProductRoute,
  ZhResultsRoute: ZhResultsRoute,
  AgentIndexRoute: AgentIndexRoute,
  ZhIndexRoute: ZhIndexRoute,
  LlmsDotmdxAgentSplatRoute: LlmsDotmdxAgentSplatRoute,
  LlmsDotmdxSiteSplatRoute: LlmsDotmdxSiteSplatRoute,
  LlmsDotmdxZhAgentSplatRoute: LlmsDotmdxZhAgentSplatRoute,
  ZhAgentSplatRoute: ZhAgentSplatRoute,
  ZhAgentApproachRoute: ZhAgentApproachRoute,
  ZhAgentCompanyRoute: ZhAgentCompanyRoute,
  ZhAgentDiagnosticRoute: ZhAgentDiagnosticRoute,
  ZhAgentGeoRoute: ZhAgentGeoRoute,
  ZhAgentPrivacyRoute: ZhAgentPrivacyRoute,
  ZhAgentProductRoute: ZhAgentProductRoute,
  ZhAgentIndexRoute: ZhAgentIndexRoute,
  ApiPlausibleEventIndexRoute: ApiPlausibleEventIndexRoute,
  ApiPlausibleJsScriptIndexRoute: ApiPlausibleJsScriptIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
